### ISSUE TITLE
The screen is not responsive.

### ISSUE THREAD

**Issue by GiovanniHD201E** [Creatures-Developer-Network/C3-WildGarden#12]
I disregard eye-glasses, despite my miopy.  In contrast, I magnify the Screen Desktop, as well the zoom in Browser. I loved your page: three major Ursache: beauty, one-way central focus, economic in clickability teaser; quality with density. There is only one column, one-way route, which help me not to be dispersive (I feel confortable as lesser options to focus, perhaps due my hyperactiv brain trend), Nevertheless, I had to zoom out to see the entire page. Consider apply changes in your CSS. If you do not bother, I will try to remember the responsivity solution for you, because your page is really beatiful. Forgive me for my English.  21 years of dispractice.

**Comment by KeyboardInterrupt** [comment]
@GiovanniHD201E What's up with the Issue ^^?
Wrong Repository?

**Comment by Amaikokonut** [comment]
Friend, what page are you referring to? There's no CSS or layout involved in this repository, so we're a little confused.
